FROM node:20

RUN apt-get update && apt-get install -y openssh-server nano net-tools

RUN echo "root:qwerty" | chpasswd
RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

ARG WORKDIR=app

WORKDIR /${WORKDIR}

COPY package.json .

RUN npm install -g typescript

RUN npm i

COPY . .
# PermitRootLogin yes
# PasswordAuthentication yes

# RUN echo "NODE_ENV=production" > .env && \
#     echo "PORT=3000" >> .env && \
#     echo "API_KEY=your_api_key_here" >> .env

RUN touch .env

EXPOSE 3000 22

CMD ["sh", "./docker-dev-launcher.sh"]
