FROM node:20-slim

RUN apt-get update && apt-get install -y openssh-server nano net-tools

RUN echo "root:qwerty" | chpasswd
RUN sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

ARG WORKDIR=app

WORKDIR /${WORKDIR}

COPY package.json .

RUN npm install -g typescript

RUN npm i

COPY . .

RUN touch .env

EXPOSE 3000 22

CMD ["sh", "./docker-dev-launcher.sh"]
