services:
    nginx:
        container_name: smilebaby_nginx_dev
        build:
            context: "./nginx/"
            dockerfile: dockerfile
            args:
              WORKDIR: "."
        ports:
            - '8080:80'
        depends_on:
            nextjs:
                condition: service_started
        restart: always
        develop:
          watch:
            - path: ./nginx/nginx.conf 
              target: /etc/nginx/nginx.conf
              action: sync+restart
            - path: ./nginx/route.conf 
              target: /etc/nginx/conf.d/default.conf
              action: sync+restart
        
    postgres:
        container_name: smilebaby_postgres_dev
        image: postgres:16.4-alpine
        restart: always
        expose:
            - '5432'
        ports:
            - "15432:5432"
        env_file: .env.dev
        volumes:
            - /var/postgres_data:/var/lib/postgresql/data
    
    nestjs:
        container_name: smilebaby_nestjs_dev
        build: 
            context: './backend/'
            dockerfile: dockerfile
            target: dev
            args:
              APPDIR: "."
            
        restart: always
        expose:
            - '3001'
        ports:
          - '34560:34560'
        env_file: .env.dev
        depends_on:
            postgres:
                condition: service_started
        develop:
          watch:
            - path: ./backend/
              action: sync
              target: /app
              ignore:
                - node_modules
                - dist
                - .vscode
        volumes:
        - ./shared/:/shared:ro
    nextjs:
        container_name: smilebaby_nextjs_dev
        build: 
            context: './frontend/'
            dockerfile: dockerfile
            target: dev
            args:
              APPDIR: "."
        expose:
            - '3000'
        ports:
          - "2222:22"
          - "9229:9229"
        restart: always
        depends_on:
            nestjs:
                condition: service_started
        develop:
          watch:
            - path: ./frontend/
              action: sync
              target: /app
              ignore:
                - node_modules
                - .next
                - .vscode
                - dist
        volumes:
        - ./shared/:/shared:ro
        env_file: .env.dev
