services:
    nginx:
        container_name: smilebaby_nginx
        build:
            context: "./nginx/"
            dockerfile: dockerfile
        ports:
            - '80:80'
        depends_on:
            - nextjs
        
    postgres:
        container_name: smilebaby_postgres
        image: postgres:16.4-alpine
        expose:
            - '5432'
        ports:
            - "15432:5432"
        env_file: .env.dev
        volumes:
            - /var/postgres_data:/var/lib/postgresql/data
    
    nestjs:
        container_name: smilebaby_nestjs
        build: 
            context: './backend/'
            dockerfile: dockerfile
        expose:
            - '3001'
        ports:
          - '34560:34560'
        env_file: .env.dev
        depends_on:
            - postgres
        volumes:
        - ./backend/src:/app/src
        - ./backend/types:/backend/types
        - ./shared/:/shared:ro
    nextjs:
        container_name: smilebaby_nextjs
        build: 
            context: './frontend/'
            dockerfile: dockerfile
        expose:
            - '3000'
        ports:
          - "2222:22"
        depends_on:
            - nestjs
        volumes:
        - ./frontend/src:/app/src
        - ./frontend/public:/app/public
        - ./frontend/types:/app/types
        - ./shared/:/shared:ro
        env_file: .env.dev
