services:
    nginx:
        container_name: smilebaby_nginx
        build:
            context: "./nginx/"
            dockerfile: dockerfile
        ports:
            - '80:80'
        depends_on: ["nextjs"]
        
    postgres:
        container_name: smilebaby_postgres
        image: postgres:16.4-alpine
        expose:
            - '5432'
        env_file: .env.prod
        volumes:
            - /var/postgres_data:/var/lib/postgresql/data
    
    nestjs:
        container_name: smilebaby_nestjs
        build: 
            context: './'
            dockerfile: './backend/dockerfile.prod'
        expose:
            - '3001'
        env_file: .env.prod
        depends_on: ["postgres"]
    nextjs:
        container_name: smilebaby_nextjs
        build: 
            context: './'
            dockerfile: './frontend/dockerfile.prod'
        expose:
            - '3000'
        depends_on: ["nestjs"]
        env_file: .env.prod