# Используем официальный образ Node.js в качестве основы
FROM node:18-alpine
ARG WORKDIR=app
# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /${WORKDIR}

COPY package.json .

RUN npm install -g typescript

RUN npm i
# Копируем package.json и package-lock.json (если есть)
COPY . .


# Устанавливаем зависимости


# Копируем остальные файлы проекта в рабочую директорию


# Компилируем TypeScript код в JavaScript

# Указываем команду для запуска приложения
CMD ["npm", "run", "start:debug"]

# Указываем порт, который будет слушать приложение
EXPOSE 3001
EXPOSE 34560