FROM node:20-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

COPY package.json .

RUN npm install -g typescript

RUN npm i
# Копируем package.json и package-lock.json (если есть)
COPY . .

# Устанавливаем зависимости

# Копируем остальные файлы проекта в рабочую директорию

# Компилируем TypeScript код в JavaScript
EXPOSE 3001 34560
# Указываем команду для запуска приложения
CMD ["npm" ,"run", "start:debug"]
# Указываем порт, который будет слушать приложение
